version: "3.8"

services:
  example-gin:
    image: example-gin:latest
    deploy:
      replicas: 2
      mode: replicated
    build:
      dockerfile: Dockerfile
      context: ./example-gin
    environment:
    - GIN_MODE=release
    ports:
      - 8080
  
  caddy-service:
    image: caddy-service:latest
    build:
      dockerfile: Dockerfile
      context: ./caddy
    ports:
      - 2019:2019
      - 443:443
      - 80:80
    healthcheck:
      test: curl --fail http://localhost/healthz || exit 1
      interval: 5s
      retries: 3
      start_period: 20s
      timeout: 3s